spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BigJunOba/config-repo
          username: sjy534948129@sina.com
          password: Sjy802366
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"