spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BigJunOba/config-repo
          username: sjy534948129@sina.com
          password: xxxxxxxx
  rabbitmq:
    host: 192.168.99.101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"